name: Build Native Linux

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: curiosityai/rocksdb-build-linux:latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set RocksDB version
      run: |
        ROCKSDBVNUM=$(cat rocksdbversion)
        echo "ROCKSDBVERSION=${ROCKSDBVNUM}" >> $GITHUB_ENV
      working-directory: ${{ github.workspace }}

    - name: Build RocksDB
      run: ./build-rocksdb.sh
      working-directory: ${{ github.workspace }}/build-native/

    - name: List files
      run: ls ${{ github.workspace }} -hR

    - name: Upload Linux Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-native-libs
        path: |
          ${{ github.workspace }}/build-native/runtimes/linux-x64/native/librocksdb.so
        retention-days: 7