name: Build Native Windows

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set RocksDB version
      shell: bash
      run: |
        ROCKSDBVNUM=$(cat rocksdbversion)
        echo "ROCKSDBVERSION=${ROCKSDBVNUM}" >> $GITHUB_ENV
      working-directory: ${{ github.workspace }}

    - name: Build RocksDB
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\vsdevcmd" -arch=x64 && bash build-rocksdb.sh
      working-directory: ${{ github.workspace }}/build-native/

    - name: List files
      run: ls ${{ github.workspace }} -hR

    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-native-libs
        path: |
          ${{ github.workspace }}/build-native/runtimes/win-x64/native/rocksdb.dll
        retention-days: 7