name: Build Native macOS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    env:
      HOMEBREW_CELLAR: /usr/local/Cellar/
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set RocksDB version
      run: |
        ROCKSDBVNUM=$(cat rocksdbversion)
        echo "ROCKSDBVERSION=${ROCKSDBVNUM}" >> $GITHUB_ENV
      working-directory: ${{ github.workspace }}

    - name: List initial directories
      run: |
        ls -hR /usr/lib/
        ls -hR /usr/local/

    - name: Build RocksDB
      run: ./build-rocksdb.sh
      working-directory: ${{ github.workspace }}/build-native/

    - name: Update dylib dependencies
      working-directory: ${{ github.workspace }}/build-native/runtimes/osx-x64/native/
      run: |
        otool -L librocksdb.dylib
        install_name_tool -change /usr/local/opt/snappy/lib/libsnappy.1.dylib "@loader_path/libsnappy.dylib" librocksdb.dylib
        install_name_tool -change /usr/local/opt/zstd/lib/libzstd.1.dylib "@loader_path/libzstd.dylib" librocksdb.dylib
        install_name_tool -change /usr/lib/libz.1.dylib "@loader_path/libz.dylib" librocksdb.dylib
        install_name_tool -change /usr/local/opt/lz4/lib/liblz4.1.dylib "@loader_path/liblz4.dylib" librocksdb.dylib
        otool -L librocksdb.dylib

    - name: Copy Dependencies
      run: |
        mkdir -p ${{ github.workspace }}/native-libs/osx-x64/
        cp ${{ github.workspace }}/build-native/runtimes/osx-x64/native/librocksdb.dylib ${{ github.workspace }}/native-libs/osx-x64/
        cp "/usr/local/Cellar/zlib/1.3.1/lib/libz.1.dylib" ${{ github.workspace }}/native-libs/osx-x64/libz.dylib
        cp "${{ env.HOMEBREW_CELLAR }}/lz4/1.10.0/lib/liblz4.dylib" ${{ github.workspace }}/native-libs/osx-x64/
        cp "${{ env.HOMEBREW_CELLAR }}/snappy/1.2.1/lib/libsnappy.dylib" ${{ github.workspace }}/native-libs/osx-x64/
        cp "${{ env.HOMEBREW_CELLAR }}/zstd/1.5.6/lib/libzstd.dylib" ${{ github.workspace }}/native-libs/osx-x64/

    - name: Upload macOS Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-native-libs
        path: ${{ github.workspace }}/native-libs/osx-x64/
        retention-days: 7